version: '3'
services:
    express:
        build: 
            context: . 
            dockerfile: Dockerfile
        image: kapirotinha_image:local
        container_name: kapirotinha_container01
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./:/kapirotinha
            - /kapirotinha/node_modules